<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <ProjectReference Include="..\Showcase.Application\Showcase.Application.csproj" />
    <ProjectReference Include="..\Showcase.Domain\Showcase.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>

</Project>
